[mypy]
python_version = 3.12
# ВАЖНО: чтобы "apps.*" импортировались как top-level package
mypy_path = backend
explicit_package_bases = True

# Обычно достаточно для Django-проекта на старте
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
show_error_codes = True
pretty = True

# Не трогаем миграции
exclude = (?x)(
  migrations/.*)

# Django stubs plugin (включим, но он заработает только если установлен django-stubs)
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = config.settings.base
