# Generated by Django 5.0.1 on 2026-01-28 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0003_service_description_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        max_length=24,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите телефон в формате +79990000000 (можно пробелы/скобки/дефисы).",
                                regex="^\\+?\\d[\\d\\s\\-\\(\\)]{8,20}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "preferred_datetime",
                    models.DateTimeField(verbose_name="Желаемые дата/время"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("completed", "Завершена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                    models.Index(
                        fields=["preferred_datetime"],
                        name="appointment_preferr_5cba49_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("service", "preferred_datetime"), name="uniq_service_datetime"
            ),
        ),
    ]
