# Generated by Django 5.0.1 on 2026-02-24 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promos", "0001_initial"),
        ("services", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало слота")),
                ("ends_at", models.DateTimeField(verbose_name="Конец слота")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("is_booked", models.BooleanField(default=False, verbose_name="Занят")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        max_length=24,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите телефон в формате +79990000000 (можно пробелы/скобки/дефисы).",
                                regex="^\\+?\\d[\\d\\s\\-\\(\\)]{8,20}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "preferred_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата/время записи"
                    ),
                ),
                (
                    "reminded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Напоминание отправлено"
                    ),
                ),
                (
                    "reminder_email_sent",
                    models.BooleanField(
                        default=False, verbose_name="Email-напоминание отправлено"
                    ),
                ),
                (
                    "reminder_telegram_sent",
                    models.BooleanField(
                        default=False, verbose_name="Telegram-напоминание отправлено"
                    ),
                ),
                (
                    "reminder_24h_sent",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание 24ч отправлено"
                    ),
                ),
                (
                    "reminder_2h_sent",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание 2ч отправлено"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("completed", "Завершена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="staff.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="promos.promo",
                        verbose_name="Акция",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.appointmentslot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["service", "starts_at"], name="appointment_service_a44c41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["is_active", "is_booked"], name="appointment_is_acti_084853_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["preferred_datetime"], name="appointment_preferr_5cba49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor"], name="appointment_doctor__649ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["service"], name="appointment_service_9ce97f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["promo"], name="appointment_promo_i_c3f8b4_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["slot"], name="appointment_slot_id_aacb8f_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slot__isnull", False)),
                fields=("slot",),
                name="uniq_appointment_slot",
            ),
        ),
    ]
