# Generated by Django 5.0.1 on 2026-02-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("services", "0004_service_featured_order_service_is_featured_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="uniq_service_datetime",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="staff.doctor",
                verbose_name="Врач",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor"], name="appointment_doctor__649ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["service"], name="appointment_service_9ce97f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("doctor__isnull", False)),
                fields=("doctor", "preferred_datetime"),
                name="uniq_doctor_datetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("service", "preferred_datetime"),
                name="uniq_service_datetime",
            ),
        ),
    ]
