# Generated by Django 5.0.1 on 2026-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=("service", "starts_at"), name="uniq_slot_service_starts_at"
            ),
        ),
    ]
