# Generated by Django 5.0.1 on 2026-02-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_remove_appointment_uniq_service_datetime_and_more"),
        ("promos", "0002_promo_services"),
        ("services", "0004_service_featured_order_service_is_featured_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="promos.promo",
                verbose_name="Акция",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["promo"], name="appointment_promo_i_c3f8b4_idx"),
        ),
    ]
