# Generated by Django 5.0.1 on 2026-03-01 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointmentslot_uniq_slot_service_starts_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите телефон в формате E.164: +79991234567",
                        regex="^\\+[1-9]\\d{1,14}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
