# Generated by Django 5.0.1 on 2026-02-04 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_promo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Напоминание отправлено"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание 24ч отправлено"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2h_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание 2ч отправлено"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_email_sent",
            field=models.BooleanField(
                default=False, verbose_name="Email-напоминание отправлено"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_telegram_sent",
            field=models.BooleanField(
                default=False, verbose_name="Telegram-напоминание отправлено"
            ),
        ),
    ]
