# Generated by Django 5.0.1 on 2026-02-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_email_appointment_reminded_at_and_more"),
        ("promos", "0002_promo_services"),
        ("services", "0004_service_featured_order_service_is_featured_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало слота")),
                ("ends_at", models.DateTimeField(verbose_name="Конец слота")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("is_booked", models.BooleanField(default=False, verbose_name="Занят")),
            ],
            options={
                "ordering": ("starts_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="uniq_doctor_datetime",
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="uniq_service_datetime",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="preferred_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время"
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.appointmentslot",
                verbose_name="Слот",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("doctor__isnull", False), ("preferred_datetime__isnull", False)
                ),
                fields=("doctor", "preferred_datetime"),
                name="uniq_doctor_datetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("service__isnull", False), ("preferred_datetime__isnull", False)
                ),
                fields=("service", "preferred_datetime"),
                name="uniq_service_datetime",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["service", "starts_at"], name="appointment_service_a44c41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["is_active", "is_booked"], name="appointment_is_acti_084853_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=("service", "starts_at"), name="uniq_service_starts_at"
            ),
        ),
    ]
