# Generated by Django 5.0.1 on 2026-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointmentslot_and_more"),
        ("promos", "0002_promo_services"),
        ("services", "0004_service_featured_order_service_is_featured_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="uniq_doctor_datetime",
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="uniq_service_datetime",
        ),
        migrations.RemoveConstraint(
            model_name="appointmentslot",
            name="uniq_service_starts_at",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="preferred_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата/время записи"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["slot"], name="appointment_slot_id_aacb8f_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slot__isnull", False)),
                fields=("slot",),
                name="uniq_appointment_slot",
            ),
        ),
    ]
