# Generated by Django 5.0.1 on 2026-01-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("name",),
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Категория услуг",
                "verbose_name_plural": "Категории услуг",
            },
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="services_se_slug_4657d0_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="services_se_is_acti_91b7ea_idx",
        ),
        migrations.RemoveField(
            model_name="service",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="service",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="service",
            name="price_from",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Цена от"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="price_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена до",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
