# Generated by Django 5.0.1 on 2026-02-02 23:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_description_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="featured_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок на главной"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Показывать на главной"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_from",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Цена от",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Цена до",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="services_se_is_acti_bfbbaa_idx",
            ),
        ),
    ]
