from decimal import Decimal

import pytest
from django.core.exceptions import ValidationError
from django.test import RequestFactory
from django.urls import reverse

from apps.services.context_processors import popular_services
from apps.services.models import Service, ServiceCategory

pytestmark = pytest.mark.django_db


# -----------------------------------------------------------------------------
# Model tests
# -----------------------------------------------------------------------------
def test_service_category_str_and_slug_autofill():
    cat = ServiceCategory.objects.create(name="УЗИ", slug="")
    assert str(cat) == "УЗИ"
    assert cat.slug  # autogenerated
    assert " " not in cat.slug


def test_service_str_and_slug_autofill():
    cat = ServiceCategory.objects.create(name="УЗИ", slug="uzi")
    svc = Service.objects.create(
        category=cat,
        name="УЗИ брюшной полости",
        slug="",
        price_from=Decimal("100.00"),
    )
    assert str(svc) == "УЗИ брюшной полости"
    assert svc.slug


def test_service_clean_rejects_price_to_less_than_price_from():
    cat = ServiceCategory.objects.create(name="Анализы", slug="analizy")
    svc = Service(
        category=cat,
        name="Анализ крови",
        slug="analiz-krovi",
        price_from=Decimal("500.00"),
        price_to=Decimal("100.00"),
    )
    with pytest.raises(ValidationError) as exc:
        svc.clean()

    assert "price_to" in exc.value.message_dict


# -----------------------------------------------------------------------------
# Context processor tests
# -----------------------------------------------------------------------------
def test_popular_services_context_returns_featured_sorted_and_limited():
    cat = ServiceCategory.objects.create(name="УЗИ", slug="uzi", is_active=True)

    # Create 5 featured -> should return only first 4 by featured_order then name
    Service.objects.create(
        category=cat, name="B", slug="b", price_from=Decimal("100.00"),
        is_active=True, is_featured=True, featured_order=2,
    )
    Service.objects.create(
        category=cat, name="A", slug="a", price_from=Decimal("100.00"),
        is_active=True, is_featured=True, featured_order=2,
    )
    Service.objects.create(
        category=cat, name="C", slug="c", price_from=Decimal("100.00"),
        is_active=True, is_featured=True, featured_order=1,
    )
    Service.objects.create(
        category=cat, name="D", slug="d", price_from=Decimal("100.00"),
        is_active=True, is_featured=True, featured_order=3,
    )
    Service.objects.create(
        category=cat, name="E", slug="e", price_from=Decimal("100.00"),
        is_active=True, is_featured=True, featured_order=4,
    )

    rf = RequestFactory()
    request = rf.get("/")
    ctx = popular_services(request)

    qs = list(ctx["popular_services"])
    assert len(qs) == 4
    # first should be featured_order=1 -> C
    assert qs[0].slug == "c"


# -----------------------------------------------------------------------------
# Views tests
# -----------------------------------------------------------------------------
def _create_services_dataset():
    active_cat = ServiceCategory.objects.create(name="УЗИ", slug="uzi", is_active=True)
    inactive_cat = ServiceCategory.objects.create(name="Скрытая", slug="hidden", is_active=False)

    # Active services in active category
    s1 = Service.objects.create(
        category=active_cat, name="УЗИ сердца", slug="uzi-serdca",
        price_from=Decimal("100.00"), is_active=True, is_featured=True, featured_order=1,
    )
    s2 = Service.objects.create(
        category=active_cat, name="УЗИ сосудов", slug="uzi-sosudov",
        price_from=Decimal("200.00"), is_active=True, is_featured=False,
    )
    s3 = Service.objects.create(
        category=active_cat, name="УЗИ печени", slug="uzi-pecheni",
        price_from=Decimal("300.00"), is_active=True, is_featured=False,
    )

    # Inactive service (should not appear)
    Service.objects.create(
        category=active_cat, name="Неактивная", slug="inactive",
        price_from=Decimal("150.00"), is_active=False,
    )

    # Service in inactive category (should not appear)
    Service.objects.create(
        category=inactive_cat, name="Категория скрыта", slug="hidden-cat",
        price_from=Decimal("150.00"), is_active=True,
    )

    return active_cat, s1, s2, s3


def test_service_list_view_basic(client):
    _create_services_dataset()

    url = reverse("services:list")
    resp = client.get(url)

    assert resp.status_code == 200
    services = list(resp.context["services"])
    assert all(s.is_active for s in services)
    # inactive service and service in inactive category excluded
    slugs = {s.slug for s in services}
    assert "inactive" not in slugs
    assert "hidden-cat" not in slugs


def test_service_list_view_saves_return_url_in_session(client):
    _create_services_dataset()

    url = reverse("services:list") + "?q=узи&sort=-price"
    resp = client.get(url)
    assert resp.status_code == 200
    assert client.session.get("services_return_url") == "/services/?q=%D1%83%D0%B7%D0%B8&sort=-price"


def test_service_list_view_filter_by_category(client):
    cat, *_ = _create_services_dataset()

    url = reverse("services:category", kwargs={"category_slug": cat.slug})
    resp = client.get(url)

    assert resp.status_code == 200
    services = list(resp.context["services"])
    assert all(s.category_id == cat.id for s in services)


def test_service_list_view_search_q(client):
    _create_services_dataset()

    url = reverse("services:list") + "?q=печени"
    resp = client.get(url)

    assert resp.status_code == 200
    slugs = [s.slug for s in resp.context["services"]]
    assert slugs == ["uzi-pecheni"]


def test_service_list_view_price_range_filters(client):
    _create_services_dataset()

    url = reverse("services:list") + "?price_min=150&price_max=250"
    resp = client.get(url)

    assert resp.status_code == 200
    slugs = [s.slug for s in resp.context["services"]]
    assert slugs == ["uzi-sosudov"]


def test_service_list_view_sorting_by_price_desc(client):
    _create_services_dataset()

    url = reverse("services:list") + "?sort=-price"
    resp = client.get(url)

    assert resp.status_code == 200
    slugs = [s.slug for s in resp.context["services"]]
    # active: 100,200,300 -> desc => 300,200,100
    assert slugs == ["uzi-pecheni", "uzi-sosudov", "uzi-serdca"]


def test_service_detail_view_ok_for_active_service(client):
    _, s1, *_ = _create_services_dataset()

    url = reverse("services:detail", kwargs={"slug": s1.slug})
    resp = client.get(url)

    assert resp.status_code == 200
    assert resp.context["service"].slug == s1.slug
    assert "categories" in resp.context


def test_service_detail_view_404_for_inactive_service(client):
    cat = ServiceCategory.objects.create(name="УЗИ", slug="uzi", is_active=True)
    Service.objects.create(
        category=cat, name="Неактивная", slug="inactive",
        price_from=Decimal("100.00"), is_active=False,
    )

    url = reverse("services:detail", kwargs={"slug": "inactive"})
    resp = client.get(url)

    assert resp.status_code == 404


def test_service_detail_view_404_for_inactive_category(client):
    cat = ServiceCategory.objects.create(name="Скрытая", slug="hidden", is_active=False)
    Service.objects.create(
        category=cat, name="Услуга", slug="svc",
        price_from=Decimal("100.00"), is_active=True,
    )

    url = reverse("services:detail", kwargs={"slug": "svc"})
    resp = client.get(url)

    assert resp.status_code == 404