# Generated by Django 5.0.1 on 2026-02-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="doctors/", verbose_name="Фото"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="Стаж (лет)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Специальность"),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("time_from", models.TimeField(verbose_name="С")),
                ("time_to", models.TimeField(verbose_name="До")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="staff.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание врача",
                "verbose_name_plural": "Расписания врачей",
                "ordering": ("doctor", "weekday", "time_from"),
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="doctors",
                to="staff.specialty",
                verbose_name="Специальности",
            ),
        ),
    ]
