# Generated by Django 5.0.1 on 2026-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        upload_to="licenses/", verbose_name="Файл (PDF/изображение)"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="licenses/previews/",
                        verbose_name="Превью (опционально)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Сортировка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Лицензия/сертификат",
                "verbose_name_plural": "Лицензии/сертификаты",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
    ]
