# Generated by Django 5.0.1 on 2026-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликована"),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=220, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
