# Generated by Django 5.0.1 on 2026-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminTelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отправлено"),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Отправлено"),
                ),
            ],
            options={
                "verbose_name": "Сообщение в Telegram",
                "verbose_name_plural": "Сообщения в Telegram",
            },
        ),
    ]
