# Generated by Django 5.0.1 on 2026-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=180, unique=True, verbose_name="Slug"),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Напр.: Скидка, Чек-ап, Ночь",
                        max_length=32,
                        verbose_name="Бейдж",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=220, verbose_name="Подзаголовок"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="promos/",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(default="Подробнее", max_length=48, verbose_name="Текст кнопки"),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Напр.: /services/?q=МРТ или https://…",
                        max_length=255,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Окончание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Сортировка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promos",
                        to="services.service",
                        verbose_name="Услуги по акции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
    ]
