# Generated by Django 5.0.1 on 2026-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promos", "0001_initial"),
        ("services", "0004_service_featured_order_service_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="promos",
                to="services.service",
                verbose_name="Услуги по акции",
            ),
        ),
    ]
