# Generated by Django 5.0.1 on 2026-02-24 14:46

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=24,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите телефон в формате +79990000000 (можно пробелы/скобки/дефисы).",
                        regex="^\\+?\\d[\\d\\s\\-\\(\\)]{8,20}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
