# Generated by Django 5.0.1 on 2026-03-01 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_normalize_existing_phones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_raw",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                db_index=True,
                help_text="Формат хранения: E.164 (например +79991234567).",
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите телефон в формате E.164: +79991234567",
                        regex="^\\+[1-9]\\d{1,14}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
